#!/bin/sh

### BEGIN INIT INFO
# Provides:          omgparser
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init script for OMG!Ubuntu parser
# Description:       starts the main.py of omgparser
### END INIT INFO

# Author: Daniel Waller <2waller@informatik.uni-hamburg.de>
PATH=/opt/omgubuntu/parser
PIDFILE=/var/run/$NAME.pid
NAME=omgparser
DESC="Parser that pulls rss feed data and makes it available as json"
DAEMON=$PATH/main.py

#
# Function that starts the daemon/service
#

# Return
#   0 if daemon has been started
#   1 if daemon was already running
#   2 if daemon could not be started
do_start() {
  start-stop-daemon --start --quiet ${PIDFILE:+--pidfile ${PIDFILE}} \
	    --startas $DAEMON --name $NAME --exec $DAEMON --test > /dev/null \
	    || return 1

  start-stop-daemon --start --quiet ${PIDFILE:+--pidfile ${PIDFILE}} \
	    --startas $DAEMON --name $NAME --exec $DAEMON \
	    || return 2
}

#
# Function that stops the daemon/service
#

# Return
#   0 if daemon has been stopped
#   1 if daemon was already stopped
#   2 if daemon could not be stopped
#   other if a failure occurred
do_stop() {
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
	    ${PIDFILE:+--pidfile ${PIDFILE}} --name $NAME --exec $DAEMON
  RETVAL="$?"
  rm -f $PIDFILE
  return $RETVAL
}
